SELECT CAR_ID, round(avg(DATEDIFF(end_date, start_date)) + 1, 1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY car_id
having AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION desc, car_id desc
